package com.whys.staticDatas;

public class EthicalRules {

	public static final String DATA = "<P STYLE='margin-bottom: 0cm'><FONT SIZE=3>Notre &eacute;quipe est"
			+" compos&eacute;e de d&eacute;veloppeurs, qui sont &eacute;galement"
			+" hackers. C'est pourquoi, au sein de cette &eacute;quipe, nous avons"
			+" mis en place des r&egrave;gles d'&eacute;thiques, l'&eacute;quipe a"
			+" jug&eacute; bon de vous en tenir inform&eacute;&nbsp;:</FONT></P>"
			+" <P STYLE='margin-bottom: 0cm'><BR>"
			+" </P>"
			+" <UL>"
			+" <LI><P STYLE='margin-bottom: 0cm'><FONT SIZE=3>Aucune Information"
			+" provenant d'un scan d'un site de l'un de nos clients ne sort de"
			+" notre base de donn&eacute;es.</FONT></P>"
			+" <LI><P STYLE='margin-bottom: 0cm'><FONT SIZE=3>Toutes les personnes"
			+" d&eacute;veloppant l'application sont des Hackers White Hat (cf."
			+" <a style='text-decoration: none;' href='http://fr.wikipedia.org/wiki/White_hat'>wikipedia</a>), ils sont ce qu'on appelle des &laquo;&nbsp;ethical"
			+" hackers&nbsp;&raquo;, aucun des membres de l'&eacute;quipe n'a pour"
			+" but d'exploiter des failles quelques soient leur type. </FONT>"
			+" </P>"
			+" <LI><P STYLE='margin-bottom: 0cm'><FONT SIZE=3>Un client ne peut"
			+" avoir de d&eacute;tails sur un scan de site si ce site n'a pas &eacute;t&eacute;"
			+" confirm&eacute; comme &eacute;tant sous l'administration de"
			+" celui-ci.</FONT></P>"
			+" <LI><P STYLE='margin-bottom: 0cm'><FONT SIZE=3>Toutes les actions"
			+" faites sur le site, m&ecirc;me si celles-ci sont faites par nos"
			+" d&eacute;veloppeurs, sont trac&eacute;es sur des &eacute;crits"
			+" accessibles uniquement par l'administrateur en chef, qui est le"
			+" fondateur du projet.</FONT></P>"
			+" <LI><P STYLE='margin-bottom: 0cm'><FONT SIZE=3>Vous &ecirc;tes la"
			+" seule personne ayant acc&egrave;s aux d&eacute;tails des scans de"
			+" votre site, et &agrave; tout moment, vous pouvez nous demander plus"
			+" d'informations ou des scans personnalis&eacute;s (analyse de temps"
			+" de r&eacute;ponse en fonction des paquets/secondes par exemple).</FONT></P>"
			+" <LI><P STYLE='margin-bottom: 0cm'><FONT SIZE=3>Lors de la"
			+" suppression d'un site depuis la liste d'un utilisateur, aucune"
			+" donn&eacute;e r&eacute;siduelle n'est conserv&eacute;e. Toute"
			+" suppression est d&eacute;finitive pour des raisons de s&eacute;curit&eacute;,"
			+" vous avez donc un contr&ocirc;le total sur les donn&eacute;es"
			+" associ&eacute;es &agrave; votre site.</FONT></P>"
			+" </UL>";
}
